In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
pp=pd.read_csv("0000000000002419_training_ccpp_x_y_train.csv")
pp.shape

(7176, 5)

In [3]:
pp

        # T      V       AP     RH      EP
0      8.58  38.38  1021.03  84.37  482.26
1     21.79  58.20  1017.21  66.74  446.94
2     16.64  48.92  1011.55  78.76  452.56
3     31.38  71.32  1009.17  60.42  433.44
4      9.20  40.03  1017.05  92.46  480.38
5     26.82  69.23  1013.28  50.86  436.36
6      9.48  40.80  1023.82  78.98  485.36
7      9.41  41.54  1019.48  82.19  481.59
8     31.03  69.59  1007.77  63.96  432.56
9     18.24  59.15  1012.00  84.40  449.48
10    19.96  39.53  1006.16  62.77  460.49
11    14.43  39.82  1012.56  78.52  470.17
12    14.38  40.71  1023.46  66.12  473.41
13     5.23  35.57  1026.23  79.38  488.50
14    14.43  41.76  1024.02  83.57  467.33
15    29.81  73.67  1005.60  60.91  430.67
16    17.79  43.52  1020.65  68.29  458.57
17    22.95  63.94  1013.91  81.52  438.33
18    18.94  48.70  1008.50  94.83  451.38
19    28.01  64.69  1007.61  58.45  440.23
20    28.08  59.14  1016.16  58.08  438.83
21    13.57  42.99  1007.51  88.95  472.04
22    11.36  41.48  1012.80  76.16  465.37
23    25.99  59.54  1007.78  74.48  441.32
24    15.19  41.43  1011.34  89.67  470.41
25    23.94  51.95  1008.18  71.87  451.84
26    28.56  74.22  1007.45  69.60  434.54
27    22.71  75.23  1010.48  76.86  444.00
28     6.30  39.33  1010.63  94.26  489.95
29    11.19  40.64  1020.57  84.49  472.86
...     ...    ...      ...    ...     ...
7146  29.63  69.71  1009.04  67.26  435.27
7147  22.91  60.07  1016.03  59.72  446.19
7148  10.60  41.46  1021.23  89.02  481.30
7149  18.18  61.87  1008.64  66.28  453.10
7150  21.73  69.05  1001.31  86.64  439.01
7151  26.13  71.25   999.80  88.47  430.60
7152  14.51  44.84  1023.23  82.33  465.09
7153  26.17  66.54  1002.23  75.60  433.81
7154  26.75  69.45  1013.88  53.65  434.57
7155  12.61  41.58  1020.17  85.18  463.36
7156  10.20  41.46  1019.12  83.26  480.11
7157  21.11  43.43  1010.10  62.62  447.83
7158  25.03  60.27  1017.90  72.04  438.24
7159  27.57  69.84  1004.91  68.37  426.60
7160  27.98  71.98  1005.58  81.00  428.44
7161  10.31  37.50  1008.55  99.31  474.16
7162  26.38  49.50  1012.82  37.19  457.81
7163  11.71  40.05  1014.49  86.09  471.49
7164   9.64  39.35  1015.10  91.76  479.81
7165  28.62  63.77  1012.82  55.77  441.97
7166  27.94  69.84  1003.11  70.47  428.67
7167  33.60  74.33  1012.31  35.66  428.62
7168  22.84  71.25  1001.90  96.45  433.85
7169  10.59  41.46  1016.87  85.70  480.83
7170  28.07  68.08  1013.13  44.67  437.65
7171   9.32  37.73  1022.14  79.49  477.91
7172  11.20  41.38  1021.65  61.89  476.87
7173  29.80  69.34  1009.36  64.74  437.65
7174  16.37  54.30  1017.94  63.63  459.97
7175  30.11  62.04  1010.69  47.96  444.42

[7176 rows x 5 columns]

In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
x_train=pp.iloc[:,0:4]

In [6]:
x_train.shape

(7176, 4)

In [7]:
y_train=pp.iloc[:,4:5]
y_train.shape

(7176, 1)

In [8]:
scaler=StandardScaler()

In [9]:
clf=LinearRegression()

In [10]:
x_trainScaled=scaler.fit_transform(x_train)

In [11]:
x_test=pd.read_csv("0000000000002419_test_ccpp_x_test.csv")

In [12]:
x_testSCaled=scaler.transform(x_test)

In [13]:
clf.fit(x_trainScaled,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [14]:
yp=clf.predict(x_testSCaled)

In [15]:
yp.shape

(2391, 1)

In [16]:
yp

array([[471.76632733],
       [433.85647002],
       [457.23359511],
       ...,
       [439.13871988],
       [450.65930697],
       [447.27281902]])

In [17]:
df=pd.DataFrame(yp)

In [22]:
df.to_csv("Solution.csv",index=False,encoding='utf-8')

In [23]:
ans=pd.read_csv("Solution.csv")

In [24]:
ans.shape

(2391, 1)

In [25]:
ans

               0
0     471.766327
1     433.856470
2     457.233595
3     464.610406
4     448.169439
5     478.272974
6     446.702020
7     483.841277
8     439.952216
9     434.271733
10    431.698354
11    472.412455
12    463.054410
13    444.068077
14    456.560736
15    488.141780
16    447.637864
17    426.652219
18    438.240404
19    439.401166
20    483.099904
21    459.753326
22    475.419601
23    431.432422
24    434.108822
25    467.563085
26    470.087542
27    432.407206
28    476.505536
29    443.212927
...          ...
2361  433.798284
2362  444.963589
2363  430.015609
2364  451.479153
2365  477.635474
2366  464.877421
2367  467.476314
2368  470.592691
2369  461.911974
2370  426.699794
2371  440.544630
2372  449.700863
2373  432.138100
2374  454.640611
2375  437.422791
2376  472.707448
2377  433.784057
2378  467.435198
2379  468.110104
2380  462.821028
2381  451.154064
2382  470.134762
2383  467.109501
2384  447.636775
2385  431.623708
2386  433.752670
2387  440.188032
2388  439.138720
2389  450.659307
2390  447.272819

[2391 rows x 1 columns]